KOSA-DBCS/WorkForce

- .gitignore
- pom.xml
- src/main/java/kr/co/dbcs/domain/AttRecordDTO.java
- src/main/java/kr/co/dbcs/domain/DeptDTO.java
- src/main/java/kr/co/dbcs/domain/EmpDTO.java
- src/main/java/kr/co/dbcs/domain/LeaveDTO.java
- src/main/java/kr/co/dbcs/domain/LeaveTypeDTO.java
- src/main/java/kr/co/dbcs/domain/PosDTO.java
- src/main/java/kr/co/dbcs/domain/SalDTO.java
- src/main/java/kr/co/dbcs/domain/UserDTO.java
- src/main/java/kr/co/dbcs/util/JdbcManager.java
- src/main/java/kr/co/dbcs/view/Main.java
- src/main/resources/log4j.xml
- src/test/java/kr/co/dbcs/view/JdbcTest.java
- JdbcManager
- DTO(User, Pos, Dept, Emp, Leave, LeaveType, Sal, AttRecord)
- JDBC jUnit Test
> [Add JDBC, DTO, jUnit Test]

- src/main/java/kr/co/dbcs/service/UserService.java
- src/main/java/kr/co/dbcs/service/UserServiceImpl.java
- src/main/java/kr/co/dbcs/util/Validation.java
- src/main/java/kr/co/dbcs/view/Main.java
회원가입과 로그인을 위한 Validation 클래스 생성 : 정규식을 통한 검증
User Service 인터페이스와 클래스 생성.. 현재 기능 구현 시작
> [make Validation Util & UserService Class]

- src/main/java/kr/co/dbcs/domain/AttRecordDTO.java
- src/main/resources/kr.co.dbcs.sql/AttRecord.sql
- src/main/resources/kr.co.dbcs.sql/Dept.sql
- src/main/resources/kr.co.dbcs.sql/Emp.sql
- src/main/resources/kr.co.dbcs.sql/Leave.sql
- src/main/resources/kr.co.dbcs.sql/Leavetype.sql
- src/main/resources/kr.co.dbcs.sql/Pos.sql
- src/main/resources/kr.co.dbcs.sql/Sal.sql
- src/main/resources/kr.co.dbcs.sql/Usr.sql
> [Add Table DDL]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/service/UsrService.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
- src/main/java/kr/co/dbcs/util/LoginSHA.java
- src/main/java/kr/co/dbcs/view/Main.java
커넥션 문제로 발생한 회원가입 오류 고침
암호 암호화 복호화 준비.. 암호화는 되는데 복호화가 아직 안됨
> [error fix because of connection & ready to encoding password]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
싱글톤 패턴으로 변화한 내용으로 SignUp & SignIn Code
기능 돌아가는 것 확인함
> [change pattern]

- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
> [finished encoding password using sha512 & Hex]

- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
- src/main/java/kr/co/dbcs/util/LoginSHA.java
> [solve error in login because random Method in loginSHA]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/domain/AttRecordDTO.java
- src/main/java/kr/co/dbcs/service/AdminService.java
- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/AttRecordService.java
- src/main/java/kr/co/dbcs/service/AttRecordServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpService.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- src/main/java/kr/co/dbcs/service/LeaveService.java
- src/main/java/kr/co/dbcs/service/LeaveServiceImpl.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
> [Add Service Interface]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/domain/AttRecordDTO.java
- src/main/java/kr/co/dbcs/domain/DeptDTO.java
- src/main/java/kr/co/dbcs/domain/EmpDTO.java
- src/main/java/kr/co/dbcs/domain/LeaveDTO.java
- src/main/java/kr/co/dbcs/domain/PosDTO.java
- src/main/java/kr/co/dbcs/domain/SalDTO.java
- src/main/java/kr/co/dbcs/domain/UsrDTO.java
- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/AttRecordServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- src/main/java/kr/co/dbcs/service/LeaveServiceImpl.java
> [Encapsulate Field]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/domain/UsrDTO.java
- src/main/java/kr/co/dbcs/service/LeaveServiceImpl.java
- src/main/java/kr/co/dbcs/service/UsrService.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
encapsulation using DTO
sending UsrDTO to HomeController
> [encapsulation using DTO]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/domain/EmpDTO.java
- src/main/java/kr/co/dbcs/domain/UsrDTO.java
- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/AttRecordServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpService.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- src/main/java/kr/co/dbcs/service/LeaveServiceImpl.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
- src/main/java/kr/co/dbcs/util/JdbcManager.java
- src/main/java/kr/co/dbcs/view/Main.java
- Update Singleton Pattern, Encapsulation
> [Update Singleton Pattern]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/domain/EmpDTO.java
- src/main/java/kr/co/dbcs/domain/LeaveDTO.java
- src/main/java/kr/co/dbcs/domain/LeaveTypeDTO.java
- src/main/java/kr/co/dbcs/service/AttRecordServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
- src/main/java/kr/co/dbcs/util/JdbcManager.java
- src/main/resources/kr.co.dbcs.sql/Leave.sql
- src/main/resources/kr.co.dbcs.sql/LeaveType.sql
> [Add LeaveType]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/service/AdminService.java
- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
관리자 뷰 생성
관리자만 관리자 아이디에 들어올 수 있게 설정
> [make administrator view & lock admin]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/service/AdminService.java
- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/AttService.java
- src/main/java/kr/co/dbcs/service/AttServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpService.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- src/main/java/kr/co/dbcs/service/LeaveService.java
- src/main/java/kr/co/dbcs/service/LeaveServiceImpl.java
- src/main/java/kr/co/dbcs/service/UsrService.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
- src/main/java/kr/co/dbcs/util/JdbcManager.java
- src/main/java/kr/co/dbcs/util/LoginSHA.java
- src/main/java/kr/co/dbcs/util/Validation.java
- src/test/java/kr/co/dbcs/view/JdbcTest.java
> [Update Password, Contact]

- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
> [Debug Update Password]

- src/main/java/kr/co/dbcs/controller/HomeController.java
- src/main/java/kr/co/dbcs/service/AdminService.java
- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/SalService.java
- src/main/java/kr/co/dbcs/service/SalServiceImpl.java
- src/main/java/kr/co/dbcs/service/UsrService.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
- src/main/java/kr/co/dbcs/view/Main.java
> [Make Operation Change PayDate]

- src/main/resources/kr.co.dbcs.sql/att.sql
> Modify Att.sql

- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/PosService.java
- src/main/java/kr/co/dbcs/service/PosServiceImpl.java
> [finished operation pos CRUD]

- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/AttService.java
- src/main/java/kr/co/dbcs/service/AttServiceImpl.java
- src/main/java/kr/co/dbcs/service/DeptService.java
- src/main/java/kr/co/dbcs/service/DeptServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
-Add DeptService CRUD
-Add DeptService Search
-Add Solve Null Problem
> [Add DeptService & Add AdminMenu for AttService]

- src/main/java/kr/co/dbcs/service/AttServiceImpl.java
- src/main/resources/kr.co.dbcs.sql/att.sql
- src/main/resources/kr.co.dbcs.sql/leave.sql
- src/main/resources/kr.co.dbcs.sql/sal.sql
-Att Table
create sequence Autorecord;
-Leave Table
create sequence leaveID;
-Sal Table
create sequence salrecord;
> [Add .sql Create Sequence]

- src/main/java/kr/co/dbcs/service/AttService.java
- src/main/java/kr/co/dbcs/service/AttServiceImpl.java
월별로 지각, 결근, 휴가 조회할 수 있는 기능 추가하였습니다.
근로자는 자신의 로그인 ID로만
관리자는 조회하고 싶은 ID로 조회할 수 있도록 하였습니다.
> [Add Monthly Select]

- src/main/java/kr/co/dbcs/service/AdminServiceImpl.java
- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- src/main/java/kr/co/dbcs/service/LeaveService.java
- src/main/java/kr/co/dbcs/service/LeaveServiceImpl.java
- src/main/java/kr/co/dbcs/util/JdbcManager.java
> [minor update]

- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
> [Add Search Employee]

- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- src/main/java/kr/co/dbcs/service/LeaveServiceImpl.java
- src/main/java/kr/co/dbcs/service/UsrServiceImpl.java
- src/main/java/kr/co/dbcs/util/JdbcManager.java
- src/main/java/kr/co/dbcs/util/Validation.java
- UserServiceImpl.input()
- EmpServiceImpl.updateContact()
> [Add Contact Validation]

- src/main/java/kr/co/dbcs/service/EmpServiceImpl.java
- EmpServiceImpl.showEmpInfo()
- EmpServiceImpl.searchEmp()
SQL 쿼리 개선
> [Refactor SQL]

- src/main/java/kr/co/dbcs/service/AttService.java
- src/main/java/kr/co/dbcs/service/AttServiceImpl.java
- src/main/java/kr/co/dbcs/util/JdbcManager.java
-add InsertLeave
-add searchLeave
> [Add insertLeave Service]
